name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: 
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to AWS EB
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      # Step 3: Install dependencies (optional - for testing)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run tests (optional - add tests later)
      - name: Run tests
        run: |
          echo "No tests configured yet"
          # python -m pytest tests/ when you add tests
      
      # Step 5: Create deployment package
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" \
            -x "*venv/*" \
            -x "*__pycache__/*" \
            -x "*.DS_Store" \
            -x "*logs/*" \
            -x "*.log"
      
      # Step 6: Get current timestamp for version label
      - name: Get timestamp
        id: time
        run: echo "TIME=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT
      
      # Step 7: Deploy to AWS Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: student-predict
          environment_name: student-predict-env
          version_label: "v-${{ steps.time.outputs.TIME }}-${{ github.sha }}"
          region: us-east-1
          deployment_package: deploy.zip
          wait_for_deployment: true
          wait_for_environment_recovery: 300
      
      # Step 8: Notify on success
      - name: Deployment successful
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 Your app is live!"

